@startuml Sequence Diagram
title Accusation Sequence Diagram
participant Player
participant Server
participant Board
participant Character
participant "Other Players"
Player -> Server: Accusation signal
alt Player in game
    Server -> Board: Accusation signal
    alt Accusation is correct
        par
            Board --> Player: Game over | You win
            Board -> "Other Players": Game over | You lose
        end
            Board -> Server: End game
    else Accusation is incorrect
        par
            Board --> Player: Incorrect accusation | You lose
            Board --> Character: Character eliminated
        end
    end
else Player not in game
    Server --> Player: Error
end
@enduml