@startuml Sequence Diagram
title Suggestion Sequence Diagram
participant Player
participant Server
participant Board
participant Character
participant "Other Player"
Player -> Server: Suggestion signal
alt Player in game
    Server -> Board: Suggestion signal
    Board -> Character: Check in room
    alt Character in room
        Character --> Board: Suggestion valid
    else Characer in hallway
        Character --> Board: Suggestion invalid
    end
    alt Suggestion valid
        Board -> Character: Move character to room
        loop Until a card is revealed
            Board -> "Other Player": Disproof signal
            "Other Player" -> Board: Disproof card
            Board --> Player: Reveal card
        end
    else Suggestion invalid
        Board --> Player: Error
    end
else Player not in game
    Server --> Player: Error
end
@enduml